---
title: "Project"
author: "PuRple LoosestRife"
date: "March 12, 2019"
output: html_document
---


#Week 8 GROUP Assignment

<br><br>

###1. GitHub Repo - https://github.com/SehajRaina/puRple-loosestRife.git

<br>

###2.a) Dataset - https://datadryad.org/resource/doi:10.5061/dryad.4fk53?fbclid=IwAR31jDBM0DmcN76f0uPiNXhdhSyACGjJFfPWT28UvL-EAtWH_GF8_-qfSb8

<br>

###2.b) Description - Data from: Gene amplification of 5-enol-pyruvylshikimate-3-phosphate synthase in glyphosate-resistant Kochia scoparia. These results indicate increased EPSPS expression is a mechanism for glyphosate resistance in these K. scoparia populations.

<br>

###3. Question - Based on the genetic relation between resistant individuals, does resistance evolve independently or was is spread from a few origins?

<br>

###4. Method - We would study the phylogenic relationship amongst the sequences by using alignment functions and building distance matrices which can then be visualized in various ways. We will visualise the relationships through tree construction as well as clustering of similar species to look for any evident patterns. 
