---
title: "Week9 Group Assignment"
author: "Hayley Brackenridge"
date: '2019-03-18'
output: html_document
---

# Preamble

This markdown contains the group assignment for BIOL432 week 9.

# Assignment

  1. From your individual datasets and questions, settle on one dataset and 1-3 main questions you will address using methods learned in this class.
  
  2. On your group GitHub account, post a group outline that contains:
    * Data description (including reference or link to the data)
    * Main questions to be addressed
    * Flowchart or point-form outline of main analysis steps
    * A division of labour statement – explain which parts of the analysis is each student responsible for

## Dataset

We will be looking at the following datset from this link: (http://bowtie-bio.sourceforge.net/recount/?fbclid=IwAR18Rd0buwg7OMb0XP7VuxBKXfQtWIOHHlIBRPK-ZrrkbyR_fjPrzN1sekw) containing *C. elegans* DNA from 4 developmental stages. 

With this data we will address the following questions:

  1. a) What genes are differentially expressed at different developmental stages in *C. elegans*
    b) What genes are differentially expressed in male vs female *C. elegans* 
  2. Based on the most differentiated gene across the developmental stages, is there homology in that gene amongst different species 
    * Note: this will require NCBI BLAST search and the construction of a phylogentic tree
    
## Main Analyses Steps

### Q1: Gene expression @ different stages/ sex

  * distance matrix
  * heat map
  * PCA plot

### Q2: Gene homology

  * from heat map, select gene that is most different among stages
  * BLAST search that gene to find homology
  * distance matrix of homologous genes (or proteins if very long)
  * DNA multiple alignment
  * phylogenetic tree of homologous genes
    * construct different tree types and compare
    
## Division of Labour

  1. a) Hayley
    b) Sehaj 
  2. BLAST -- Vivian
    
    Distance matrix & alignment -- Minji
    
    Phylogenetic trees -- Everyone